---
name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - release-*
      - hotfix-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tell API to deploy bot
        run: |
          curl -X POST ${{ secrets.DEPLOY_URL }} \
            -H 'Authorization: ${{ secrets.DEPLOY_TOKEN }}'